version: '3.8'

services:
  eco-tycoon:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
